# docker-compose.yml

version: '3.8'

services:
  back-probe:
    image: back_probe
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 7000:8000
